# Generated by Django 3.1 on 2020-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_education_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='role',
            field=models.CharField(default='heelo', max_length=50),
            preserve_default=False,
        ),
    ]
